# ================== SPARK REPORT ==================
extent.reporter.spark.start=true
extent.reporter.spark.out=SparkReport.html

# ================== REPORT META ==================
extent.reporter.spark.title=Automation Test Report
extent.reporter.spark.reportName=UI Automation Execution
extent.reporter.spark.theme=standard
extent.reporter.spark.timestampFormat=dd-MMM-yyyy HH:mm:ss

# ================== SCREENSHOTS ==================
extent.reporter.spark.base64imagesrc=true
extent.reporter.spark.embedImages=false

# ================== VIEW ==================
extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device

# ================== FOLDER CONTROL ==================
basefolder.name=Reports/ExtentReports
basefolder.datetimepattern=dd-MMM-yy HH-mm-ss
